development:
  adapter: postgresql
  encoding: unicode
  database: vander_movies_development
  pool: 5
  

production:
  adapter: postgresql
  encoding: unicode
  database: vander_movies_production
  pool: 5
  